logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://app-514208b4-56d5-4a46-b320-2b5e81b4351a.cleverapps.io/

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
