logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  server:
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: https://app-bb8fd4b0-fff7-4724-880b-8940ab9a1f7d.cleverapps.io/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000