server:
  port: 8066
  servlet:
    context-path: /startInformation
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      properties:
        hibernate.format_sql: true
      ddl-auto: create
    properties:
      hibernate:
    show-sql: true

---

config:
  activate:
    on-profile: local
datasource:
  platform: postgres
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver

---

config:
  activate:
    on-profile: clever_cloud
datasource:
  url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: ${POSTGRESQL_ADDON_USER}
  password: ${POSTGRESQL_ADDON_PASSWORD}
  hikari:
    maximum-pool-size: 2