spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: psd-protective-equipment-service
            uri: https://app-d60ad30b-8351-428f-bcbd-eec45a1ea266.cleverapps.io/
            predicates:
              - Path=/protectiveEquipment/*
          - id: psd-start-information-service
            uri: https://app-5a5451d7-60ea-4d7e-a097-5e1edfe4334e.cleverapps.io/
            predicates:
              - Path=/startInformation/*

server:
  port: 8989