spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: psd-protective-equipment-service
            uri: https://app-d60ad30b-8351-428f-bcbd-eec45a1ea266.cleverapps.io/
            predicates:
              - Path=/protectiveEquipment/*
          - id: psd-start-information-service
            uri: https://app-5a5451d7-60ea-4d7e-a097-5e1edfe4334e.cleverapps.io/
            predicates:
              - Path=/startInformation/*
          - id: psd-compensation-device-service
            uri: https://app-13b48729-6e00-45d0-9e3c-403547d74f06.cleverapps.io/
            predicates:
              - Path=/compensationDevice/*
          - id: psd-power-transformers-service
            uri: https://app-fdf88c24-09a2-4184-bfee-61e2e9b905ff.cleverapps.io/
            predicates:
              - Path=/powerTransformers/*

server:
  port: 8989